export const LOGIN_USER_PENDING = 'App/QUEUE_LOAD_PENDING';
export const LOGIN_USER_SUCCESS = 'App/LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'App/LOGIN_USER_ERROR';

export const LOGOUT_USER = 'App/LOGOUT_USER';

export const QUEUE_LOAD_PENDING = 'App/QUEUE_LOAD_PENDING';
export const QUEUE_LOAD_SUCCESS = 'App/QUEUE_LOAD_SUCCESS';
export const QUEUE_LOAD_ERROR = 'App/QUEUE_LOAD_ERROR';
